### ISSUE TITLE
Missing line coverage for object class declaration

### ISSUE THREAD

**Issue by n0vah** [Kotlin/kotlinx-kover#129]
I'm getting object class declaration isn't covered. I assume that object declaration should be skipped from the code coverage report.
![image](https://user-images.githubusercontent.com/29734340/150633634-1fcf62aa-d80b-42f4-8dee-1d6933720730.png)

**Comment by shanshin** [comment]
Relates #122

**Comment by shanshin** [comment]
Fixed in `0.5.0`

**Comment by eungjun-yi** [comment]
Object class declaration is still not covered when the object has only constants. (kotlin 1.8.20 / kover 0.7.2)

<img width="190" alt="image" src="https://github.com/Kotlin/kotlinx-kover/assets/1129852/ce5eec76-a6e7-4a72-bcb6-dd8494e23577">

**Comment by jpink** [comment]
I have no properties, only single function and super class. How to test `object` initialization? Should it be referenced first time inside a test?
<img width="250" alt="image" src="https://github.com/Kotlin/kotlinx-kover/assets/4598272/560ece6f-c190-4e2b-a973-2c78b8fa7dfa">
