### ISSUE TITLE
Error during class instrumentation: com.soywiz.kds.IntMap: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by soywiz** [Kotlin/kotlinx-kover#166]
* Reproduced on CI: https://github.com/korlibs/korge-next/runs/6031454990?check_suite_focus=true#step:6:256
* PR: https://github.com/korlibs/korge-next/pull/588
* Kover: 0.5.0: https://github.com/korlibs/korge-next/pull/588/files#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06R31

**Comment by shanshin** [comment]
Must be fixed in `0.6.0`, feel free to reopen if the problem reproduced again.

**Comment by soywiz** [comment]
Still reproduces:
* https://github.com/korlibs/korge/pull/938
* https://github.com/korlibs/korge/runs/8003007849?check_suite_focus=true#step:8:524

**Comment by soywiz-invideo** [comment]
@shanshin Can you reopen the issue? The issue still persists with 0.6.0 as stated in the previous comment. But I cannot reopen it myself since I don't have permissions.

**Comment by zuevmaxim** [comment]
Fixed in agent version 1.0.683

**Comment by soywiz** [comment]
> Fixed in agent version 1.0.683

What does it mean that version? How can I try it?
Not this version right?: https://github.com/Kotlin/kotlinx-kover/releases/tag/v0.6.0 since thats 0.6.x

**Comment by zuevmaxim** [comment]
@soywiz You can try kover with non-default agent version like this:
`
        kover {
            engine.set(IntellijEngine("1.0.683"))
        }
`

**Comment by shanshin** [comment]
Fixed in Kover `0.6.1`
