### ISSUE TITLE
Kotlin muiltplatrom is not supported

### ISSUE THREAD

**Issue by taymiyyah** [Kotlin/kotlinx-kover#316]
**Describe the bug**

How can I tell kover my testing report is on that path?
**Errors**
Task 'koverHtmlReport' will be skipped because no tests were executed

**Expected behavior**
test coverage file should be created 

**Reproducer**
[KoverKMM.zip](https://github.com/Kotlin/kotlinx-kover/files/10880130/KoverKMM.zip)
Fresh kmm project Android studio with kover added

is there anything similar to jacoco classDirectories in kover

```
tasks.jacocoTestReport {
val coverageSourceDirs = arrayOf(
"src/commonMain",
"src/jvmMain"
)

val classFiles = File("${buildDir}/classes/kotlin/jvm/")
        .walkBottomUp()
        .toSet()

classDirectories.setFrom(classFiles)
sourceDirectories.setFrom(files(coverageSourceDirs))

executionData
        .setFrom(files("${buildDir}/jacoco/jvmTest.exec"))


```

will be skipped because no tests were executed 

please provide as kmm example in examples file

for 7.0 alpha 

for 0.6.1 it is working

**Comment by shanshin** [comment]
Thanks for the reproducer!

Multiplatform projects are supported, however, at the moment a combination of `kotlin("multiplatform")` and `id("org.jetbrains.kotlinx.kover")` plugins is not supported.

**Comment by shanshin** [comment]
Fixed in `0.7.0-Beta`

**Comment by aplha98** [comment]
for those configration , I can confirmed that the issue not resolved 

```
koverReport {
    filters {
        excludes {
            classes("com.beno.benoShared.BuildConfig")
            packages("com.beno.benoShared.testData.*")
            packages("com.beno.benoShared.v3.*")
            packages("com.beno.benoShared.db.*")

        }
        includes {
            packages("com.beno.benoShared.*")
        }
    }
}

kover {
    useKoverTool()

    excludeTests {
        tasks("testReleaseUnitTest")
    }
}```

**Comment by shanshin** [comment]
@aplha98, please create a new issue with a detailed description of your problem.
A small reproducer project would also help.
