### ISSUE TITLE
koverHtmlReport fails randomly with "Stream closed" or "zip file closed"

### ISSUE THREAD

**Issue by technoir42** [Kotlin/kotlinx-kover#436]
**Describe the bug**
`koverHtmlReport` tasks fail randomly in a multi-project build with JVM and Android modules.

**Errors**
```
Caused by: jetbrains.coverage.report.ReportGenerationFailedException: Failed to create report directory
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.createReportDir(HTMLReportBuilderImpl.java:189)	
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.doGenerateReport(HTMLReportBuilderImpl.java:100)	
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.generateReport(HTMLReportBuilderImpl.java:93)	
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.generateReport(HTMLReportBuilderImpl.java:88)	
  at com.intellij.rt.coverage.report.Reporter.createHTMLReport(Reporter.java:67)	
  at com.intellij.rt.coverage.report.api.ReportApi.htmlReport(ReportApi.java:49)	
  at kotlinx.kover.gradle.plugin.tools.kover.HtmlReportAction.execute(KoverHtmlOrXmlReport.kt:93)
```
```
Caused by: java.lang.IllegalStateException: zip file closed
  at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
  at java.util.zip.ZipFile.getEntry(ZipFile.java:330)
  at java.util.jar.JarFile.getEntry(JarFile.java:518)
  at sun.net.www.protocol.jar.URLJarFile.getEntry(URLJarFile.java:131)
  at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:135)
  at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:175)
  at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:296)
  at java.lang.Class.getResourceAsStream(Class.java:2850)
  at jetbrains.coverage.report.impl.IOUtil.copyResource(IOUtil.java:55)
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.prepareReportDir(HTMLReportBuilderImpl.java:202)
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.createReportDir(HTMLReportBuilderImpl.java:187)
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.doGenerateReport(HTMLReportBuilderImpl.java:100)
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.generateReport(HTMLReportBuilderImpl.java:93)
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.generateReport(HTMLReportBuilderImpl.java:88)
  at com.intellij.rt.coverage.report.Reporter.createHTMLReport(Reporter.java:67)
  at com.intellij.rt.coverage.report.api.ReportApi.htmlReport(ReportApi.java:49)
  at kotlinx.kover.gradle.plugin.tools.kover.HtmlReportAction.execute(KoverHtmlOrXmlReport.kt:93)
```

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URLConnection.setUseCaches(boolean)" because "this.jarFileURLConnection" is null
  at jetbrains.coverage.report.impl.IOUtil.copyResource(IOUtil.java:55)	
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.prepareReportDir(HTMLReportBuilderImpl.java:203)	
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.createReportDir(HTMLReportBuilderImpl.java:187)	
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.doGenerateReport(HTMLReportBuilderImpl.java:100)	
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.generateReport(HTMLReportBuilderImpl.java:93)	
  at jetbrains.coverage.report.impl.html.HTMLReportBuilderImpl.generateReport(HTMLReportBuilderImpl.java:88)	
  at com.intellij.rt.coverage.report.Reporter.createHTMLReport(Reporter.java:67)	
  at com.intellij.rt.coverage.report.api.ReportApi.htmlReport(ReportApi.java:49)	
  at kotlinx.kover.gradle.plugin.tools.kover.HtmlReportAction.execute(KoverHtmlOrXmlReport.kt:93)
```

**Expected behavior**
No random failures.

**Reproducer**
The only configuration we changed is exclude some classes.
```
koverReport {
    filters {
        excludes {
            annotatedBy("javax.annotation.Generated", "javax.annotation.processing.Generated")
        }
    }
}
```

**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version: 0.7.2
 - Gradle version: 8.1.1
 - Kotlin project type: Kotlin/JVM + Kotlin/Android

**Comment by JavierSegoviaCordoba** [comment]
I see this, and it is random, sometimes it fails, and other times it works, without any change in the code, as rerunning the action usually passes.

**Comment by shanshin** [comment]
Fixed in `0.7.4`

**Comment by nicbell** [comment]
Still experiencing this randomly in `0.7.4`

**Comment by technoir42** [comment]
@shanshin can you share the commit where this was fixed?

**Comment by shanshin** [comment]
@technoir42 https://github.com/JetBrains/coverage-report/commit/11feee61da028025064d6f05a7c3d1944b1e123d

This bug appears when running code of FreeMarker inside Gradle Workers, and for most cases it resolves by re-reading resources from the jar.

The root cause was not found, because it was not possible to create a stable producer, perhaps this is due to the peculiarity of the work of the Gradle classloaders themselves, since full isolation mode is used for Gradle workers.

**Comment by nicbell** [comment]
@shanshin I still get this from time to time with `0.7.5` but not as often as before. I think the fix improved it but didn't fix it completely.
```sh
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':[removed]:koverHtmlReport'.
> A failure occurred while executing kotlinx.kover.gradle.plugin.tools.kover.HtmlReportAction
   > Failed to generate file: /builds/[removed]/build/reports/kover/html/ns-7/index_SORT_BY_BLOCK.html. zip file closed
 ```

**Comment by JavierSegoviaCordoba** [comment]
Can this be reopened?

https://github.com/JavierSegoviaCordoba/hubdle/actions/runs/7718808098/job/21040826852?pr=843

**Comment by shanshin** [comment]
@JavierSegoviaCordoba, same issue already opened https://github.com/Kotlin/kotlinx-kover/issues/510
