### ISSUE TITLE
Class with constants

### ISSUE THREAD

**Issue by clickjamper** [Kotlin/kotlinx-kover#451]
Why do you need to write tests for classes which contains only constants like

`internal object TestObject {
  const val TEST_CONST = "test_const"
}`

**Comment by shanshin** [comment]
Hi,
Kover notifies only that an object has been declared in the code that is not explicitly used anywhere.

Unfortunately, when compiling, the constant is not stored in the class, so Kover cannot determine exactly how this object will be used - independently or as a scope for grouping constants.


In this case, it is possible to exclude such classes from the report by name or using an annotation.

**Comment by zuevmaxim** [comment]
@shanshin Fixed in agent version `1.0.741`

**Comment by shanshin** [comment]
Fixed in Kover `0.7.5`

**Comment by BulatInDrive** [comment]
I updated Kover to 0.7.5, but it still shows that an object containing only constants has no tests.
<img width="292" alt="image" src="https://github.com/Kotlin/kotlinx-kover/assets/127848635/de53927c-8333-42d1-8004-c236f9f8c72a">

**Comment by shanshin** [comment]
@BulatInDrive, thanks for the report!
The problem is reproduced for string constants

**Comment by hanrw** [comment]
Same issue shows that an interface containing companion object

<img width="485" alt="Snipaste_2024-03-16_16-45-09" src="https://github.com/Kotlin/kotlinx-kover/assets/1201118/f45bc7a9-79c8-4f00-9336-dd6c03837413">

**Comment by shanshin** [comment]
Closed in favour of https://github.com/Kotlin/kotlinx-kover/issues/583
